[package]
name = "dirstat-rs"
version = "0.2.0"
authors = ["scullionw <scuw1801@usherbrooke.ca>"]
edition = "2018"
license = "MIT"
description = "A toy disk usage cli similar to windirstat"
repository = "https://github.com/scullionw/dirstat-rs"
keywords = ["cli", "disk", "usage", "tree", "windirstat"]
categories = ["command-line-utilities"]

[dependencies]
colored = "1.6.1"
structopt = "0.2.14"
rayon = "1.0.3"
pretty-bytes = "0.2.2"