[package]
name = "dirstat-rs"
version = "0.2.2"
authors = ["scullionw <scuw1801@usherbrooke.ca>"]
edition = "2018"
license = "MIT"
readme = "README.md"
description = "A disk usage cli similar to windirstat"
repository = "https://github.com/scullionw/dirstat-rs"
keywords = ["cli", "disk", "usage", "tree", "windirstat"]
categories = ["command-line-utilities"]

[dependencies]
colored = "1.7.0"
structopt = "0.2.14"
rayon = "1.0.3"
pretty-bytes = "0.2.2"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.6"
features = [
  "winerror",
]

[profile.release]
debug = true

[[bin]]
bench = false
path = "src/bin/main.rs"
name = "ds"
